### ISSUE TITLE
bower failing  to install package if storage->packages specified in .bowerrc file

### ISSUE THREAD

**Issue by dovs** [mjeanroy/bower-npm-resolver#14]
/bowerrc:
...
"storage": {
        "packages": ".env/bower_cache"
    },
...

results in the following error:

"... ENOENT ENOENT, open '<root>/.env/bower_cache/npm-resolver/compressed/.env/bower_cache/npm-resolver/compressed/chart.js-2.2.2.tgz' ..."

**Comment by mjeanroy** [comment]
Hi @dovs, it should be fixed with the latest version on master, do you confirm?

Thanks for your feedback!

**Comment by mjeanroy** [comment]
@dovs Should be fixed with version 0.7.0.
