### ISSUE TITLE
Can I use a local npm?

### ISSUE THREAD

**Issue by irbian** [mjeanroy/bower-npm-resolver#247]
Hi!

I´m having problems using the resolver. 

I´m using com.github.eirslett.frontend-maven-plugin to install a local version of node and npm, so my different builds on jenkins can use each its own version

This looks like it doesn´t work with the resolver, because it always use the npm installed globally

Do I have some option so the npm used is the one I provide?

Would be another option that the npm is included (optionally) as a dependency, so it doesn´t requires one installed globally?

**Comment by mjeanroy** [comment]
Hi @irbian, and sorry for the (very long) delay.

This resolver use `requireg` module to get the global `npm` module, and it uses different strategies,  two may interests us:

- Check for `NODE_PATH` environment variable.
- Check for `execPath`, i.e the path of the current `node` process.

The `execPath` should be enough here, but as you can see [here](https://github.com/h2non/requireg/blob/4c5fd4086dd492928a7d6d6d134f95eb23cd8c96/lib/resolvers.js#L108), it makes the assumption that the `node_modules` is located relatively to the node executable to `../lib`. With the `frontend-maven-plugin`, the `node_modules` is located in the same directory than the `node` executable. I'll probably do a Pull Request on `requireg` to improve this but  currently, it does not work in our case.

The second option is to use the `NODE_PATH` environment variable. Fortunately, as you can see [here](https://github.com/eirslett/frontend-maven-plugin#environment-variables) you can specify environment variable with the `frontend-maven-plugin` by using the configuration below:

```xml
<plugin>
    <groupId>com.github.eirslett</groupId>
    <artifactId>frontend-maven-plugin</artifactId>
    <executions>
        <execution>
            <id>install node and npm</id>
            <phase>generate-resources</phase>
            <goals>
                <goal>install-node-and-npm</goal>
            </goals>
        </execution>
        <execution>
            <id>npm install</id>
            <phase>generate-resources</phase>
            <goals>
                <goal>npm</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <nodeVersion>v10.0.0</nodeVersion>
        <environmentVariables>
            <NODE_PATH>${project.basedir}/node/node</NODE_PATH>
        </environmentVariables>
    </configuration>
</plugin>
```

The important lines here are:

```xml
<environmentVariables>
    <NODE_PATH>${project.basedir}/node/node</NODE_PATH>
</environmentVariables>
```

I think it should fix your issue.

**Comment by mjeanroy** [comment]
Closing this issue, feel free to open a new issue if something does not work as expected.
