### ISSUE TITLE
Does not play well with https://github.com/yeoman/bower-requirejs

### ISSUE THREAD

**Issue by davireis** [mjeanroy/bower-npm-resolver#3]
Hi,

Just wanted to let you know that the choice of "npm+modulename" syntax has confused bower-requirejs, which fails with:

```
Running "bowerRequirejs:target" (bowerRequirejs) task
Verifying property bowerRequirejs.target exists in config...OK
File: [no files]
Options: config="app/main.js", exclude=[], baseUrl="", transitive=false, excludeDev=false
Warning: Task "bowerRequirejs:target" failed. Use --force to continue.
```

**Comment by jakub-g** [comment]
@davireis yes, I had my tools too due to the `npm+` prefix which made the package name and its entry in `bower.json` misaligned, that's why I opened PR #2 which was just merged last week.

However my proposal only works when all the packages are under your control and you can name them all with your own prefix. For a general-purpose solution, there should probably be no prefix at all, but a regex / additional array in `.bowerrc` or `bower.json` listing which packages should be taken from npm.

**Comment by mjeanroy** [comment]
Hi,
Thanks @davireis & @jakub-g.

I am open to a different prefix or a different solution. Currently, I see two options:
- As @jakub-g suggest, provide an array (or a regex) listing packages to fetch from npm. This solution is not so hard to implement.
- Do not specify a prefix in the name of the package, but specify the npm prefix in the value (the drawback is that you will have to repeat the name of the package), for example:

```
"dependencies": {
  "jquery": "npm://jquery#~1.1.0"
}
```

I'm ok with both solution, what do you think ?

**Comment by davireis** [comment]
Hi,

Thanks a lot for the feedback. I think the best choice would be one that does not break the spec of bower.json. The value one seems to break since in https://github.com/bower/spec/blob/master/json.md it says:

"Value must be a valid semver range, a Git URL, or a URL (inc. tarball and zipball)."

Maybe ask the bower folks to explicitly allow any scheme://host/path#semver?

**Comment by jakub-g** [comment]
> "Value must be a valid semver range, a Git URL, or a URL (inc. tarball and zipball)."

They say it has to be a URL but don't say it has to be a http(s) URL, so I think something like

    "jquery": "npm://jquery#~1.1.0"

is fine. I quite like this solution, looks better than a special array to define npm deps.

**Comment by mjeanroy** [comment]
Hi,

I agree with @jakub-g, an URL does not necessarily mean that it has to be an http(s) URL ([svn resolver](http://bower.io/docs/api/#install) works like that by the way). I just [asked the question on the bower mailing list](https://groups.google.com/forum/#!topic/twitter-bower/5RbrdVgcYd8), without any objections, I will implement this solution.

**Comment by mhofman** [comment]
The URL solution would also provide a good way to handle NPM's scoped packages:

```
  "scope-my-package": "npm:@scope/my-package#^1.0.0"
```

Right now npm-resolver will happily install the scoped package, but it ends up in a sub directory, which messes up with bower's package lookup / resolution.

**Comment by mhofman** [comment]
Also it would be nice if typing:
```
bower install --save npm:@scope/my-package
```
would automatically install and figure out the right package name, i.e. a valid name coming from the bower.json file in the npm package, or a normalized name based on the npm package name (`@scope/my-package` -> `scope-my-package`)

**Comment by mhofman** [comment]
I implemented something in #4 based on the work started by @mjeanroy earlier today.

However I believe the npm scheme shouldn't use `//` since that would make the package name the authority part of the URI instead of the path or resource.
More details in the PR.

**Comment by mjeanroy** [comment]
Hi @davireis,
Did you test last versions (>= v0.3.0)? Can I close the issue?

**Comment by davireis** [comment]
Yes, just tested it and it worked like a charm. Thanks a lot for the fix!
