### ISSUE TITLE
Cannot find module 'bower-npm-resolver'

### ISSUE THREAD

**Issue by yin** [mjeanroy/bower-npm-resolver#6]
I have the bower-npm-resolver installed both locally and globally. Runing `bower install` always results in the following message:

```
bower MODULE_NOT_FOUND      Cannot find module 'bower-npm-resolver'
```

.bowerrc:

```
{
  "directory": "public/bower_components",
  "interactive": false,
  "resolvers": [
    "bower-npm-resolver"
  ]
}
```

**Comment by jakub-g** [comment]
what version of bower you have? make sure to update bower to the newest version first

**Comment by yin** [comment]
bower - v
1.7.3

npm -v
3.10.3

**Comment by mjeanroy** [comment]
That's weird, did you install bower locally or globally ? Can you show me your `package.json` file (at least, the `devDependencies` section) ?

**Comment by mjeanroy** [comment]
Hi @yin,

That's weird, it works for me.
Can you try these commandes (this will install packages locally, the last command command will use the local bower instead of the global one):

```
npm install bower --save-dev
npm install bower-npm-resolver --save-dev
./node_modules/bower/bin/bower install
```

**Comment by yin** [comment]
Same result. Seems like my bower keeps ignoring the npm module path. I could not find a case like mine. Maybe local system anomaly? I am running ubuntu 15.04, ubuntu packaged node and npm.

**Comment by tiagosiebler** [comment]
Same issue here, did you get past this?

**Comment by martinprot** [comment]
Hey
I just have the same error.
One of my libs stopped to support bower and force me to use `bower-npm-resolver`.

I can't find any binary into `node_modules/bower-npm-resolver/...`, normal?

**Comment by mjeanroy** [comment]
Hi @martinprot,
There are no binaries, `bower-npm-resolver` is just a plugin used by bower to fetch dependencies (see [here](https://bower.io/docs/pluggable-resolvers/)).

Install this resolver (globally if you bower globally, locally otherwise), then add it to your `.bowerrc` file (see [here](https://bower.io/docs/pluggable-resolvers/#using)).

**Comment by nickygerritsen** [comment]
We are now also running into the issue that bower can not find `npm:chart.js` on one machine, but not the other.

On my own machine, where it works, all goes well. If I `bower install --loglevel=debug` a package that starts with `npm` but doesn't exist on the NPM repo, I get:

```
Registry returned 404 for GET on https://registry.npmjs.org/nonexisting-dummy
```

But on the machine, where it doesn't work, we just get `ENOTFOUND Package npm:chart.js not found`.

The .bowerrc does specify the resolver on both machines.

**Comment by rickyk586** [comment]
updating bower resolved this for me
`npm install -g bower`

**Comment by mjeanroy** [comment]
I'm closing this issue since it seems to be a problem with the installation of bower (version, local vs global). Please add a comment to reopen the issue.
