### ISSUE TITLE
Is it possible to install npm package from git?

### ISSUE THREAD

**Issue by paluh** [mjeanroy/bower-npm-resolver#93]
I've searched through docs/issues and wasn't able to find information if this is possible. I've tried to install package adding these lines to `bower.json`:

      "npm+clappr-level-selector-plugin": "https://github.com/clappr/clappr-level-selector-plugin.git#0.1.10"

also

     "clappr-level-selector-plugin": "npm:https://github.com/clappr/clappr-level-selector-plugin.git#0.1.10"

also

     "clappr-level-selector-plugin": "npm:git+https://github.com/clappr/clappr-level-selector-plugin.git#0.1.10"

All above lines works fine when I'm using `package.json` and `npm`.

**Comment by mjeanroy** [comment]
@paluh This resolver use `npm pack` under the hood, so if it works with `npm pack`, it should works with `bower-npm-resolver`. I've never used this syntax, but the [documentation](https://docs.npmjs.com/cli/pack) for `npm pack` say this is ok.

**Comment by paluh** [comment]
@mjeanroy Thanks for quick answer! I'm going to investigate this further and post here my results.

**Comment by mjeanroy** [comment]
If it works with npm, it should works with `bower-npm-resolver`, I re-open the issue until I have some time to investigate ;)

FWIW, you should probably not need this resolver if all you want to do is to fetch a dependency from github, bower does it very well.

**Comment by paluh** [comment]
@mjeanroy Wow! I wasn't aware that I can install packages without `bower.json` from github. This solves my problems.

Thanks a lot!

**Comment by mjeanroy** [comment]
Since bower can fetch git/URL endpoint natively, starting with version 0.9.0, `bower-npm-resolver` will refused packages that are not valid npm package name (an URL is not a valid package name). An error message will be print to the console to give some details.
